site_name: gwas2vcf
site_url: https://mrcieu.github.io/gwas2vcf
docs_dir: mkdocs
site_dir: docs
nav:
    - Home: index.md
    - Install: install.md
    - Tutorial: tutorial.md
    - Downstream analyses: downstream.md
theme: readthedocs